name: info-bot
version: '0.1.0.0'
category: Web
author: John Children
maintainer: john.a.children@gmail.com
copyright: 2017 John Children
license: BSD3
github: jchildren/info-bot
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - InfoBot
  - InfoBot.Connection
  - InfoBot.Modules
  - InfoBot.Types
  dependencies:
  - base >=4.7 && <5
  - base-prelude
  - linklater
  - websockets
  - lens
  - aeson
  - uri-bytestring
  - bytestring
  - text
  - mtl
  - wuss
  - network
  - containers
executables:
  info-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - info-bot
    - mtl
tests:
  info-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - info-bot
